auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 10485760
  log_level: info

memberlist:
  join_members:
    - loki:7946

schema_config:
  configs:
    - from: 2021-08-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h

common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      endpoint: ${LOKI_S3_ENDPOINT}
      insecure: true
      bucketnames: ${S3_BUCKET}
      access_key_id: ${S3_KEY_ID}
      secret_access_key: ${S3_ACCESS_KEY}
      s3forcepathstyle: true
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ruler:
  storage:
    s3:
      bucketnames: loki-ruler