version: '3.8'

volumes:
  grafana-stack_minio: {}

services:
  minio:
    image: minio/minio
    container_name: minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data
    environment:
      - MINIO_ROOT_USER=${S3_KEY_ID}
      - MINIO_ROOT_PASSWORD=${S3_ACCESS_KEY}
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    expose:
      - "9000"
      - "9001"
    volumes:
      - grafana-stack_minio:/data
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
      
  loki:
    depends_on:
      - minio

  promtail:
    container_name: promtail
    depends_on:
      - loki
    image: grafana/promtail:${LOKI_VERSION}
    volumes:
      - ./test.log:/var/log/apache2/access.log
      - ./promtail/docker-config.yml:/etc/promtail/docker-config.yml
    command: -config.file=/etc/promtail/docker-config.yml
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

networks:
  monitor-net:
    driver: bridge